Added support for symfony/console 6.0
mezzio/mezzio-swoole pull request #77
Opened 2021-12-10 11:33 UTC by acelaya

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

This PR adds support for symfony/console 6, as it's a pretty popular component, and the update is pretty much backwards compatible.

2021-12-11 07:11 UTC, Ocramius requested changes

2021-12-11 07:11 UTC, Ocramius commented on composer.json
> +        "symfony/console": "^4.1 || ^5.0 || ^6.0",
Can we drop 4.x while at it?

2021-12-11 07:12 UTC, Ocramius commented
Question: does this result in a downstream BC break, due to inheritance?

2021-12-11 07:31 UTC, acelaya commented on composer.json
> +        "symfony/console": "^4.1 || ^5.0 || ^6.0",
Sure!

2021-12-11 07:32 UTC, acelaya commented
I think I don't follow. What do you mean?

2021-12-13 18:26 UTC, weierophinney commented
> Question: does this result in a downstream BC break, due to inheritance?

It shouldn't. I've used symfony/console 6 with laminas-cli versions, and had no issues with commands. The issues will be if a user is writing commands that rely on portions of the symfony/console v4 API that are not present in later versions, or changed in later versions. Since they're very conservative about changing the inheritance API, in practice, I've not seen any cases where such breakage can occur.

2021-12-13 18:29 UTC, Ocramius requested changes
`composer.lock` still requires adjusting here

2021-12-13 21:16 UTC, merged

2021-12-13 21:17 UTC, weierophinney commented
@Ocramius I updated the `composer.lock`, but the fork was locked and I could not push back to it. Hoping that the branch builds correctly; if not, I'll open another PR with a patch to resolve.

(Bonus points: bumped to laminas-coding-standard 2.3, which means I could get rid of the "ignore-platform-reqs" flag!)

2021-12-13 21:17 UTC, acelaya commented
I was about to update the composer.lock, but I guess it's not needed anymore 😅