Provide a chapter on adding a request ID
mezzio/mezzio-swoole pull request #84
Opened 2022-01-03 21:13 UTC by weierophinney

Based on a question I answered in Slack, this provides a recipe for adding a unique request ID that can then be tracked in your logs.

2022-01-03 23:46 UTC, gsteel commented on docs/book/v4/cookbook/provide-a-request-id.md
> +The answer is deceptively simple: you can provide a [delegator factory](https://docs.mezzio.dev/mezzio/v3/features/container/delegator-factories/) for decorator on thethe service that converts the Sw
There's a double "the" on this line.

2022-01-04 14:54 UTC, froschdesign requested changes

2022-01-04 14:54 UTC, froschdesign commented on docs/book/v4/cookbook/provide-a-request-id.md
> +This poses a problem: normally you will use middleware to propagate changes to the request.
Until here the problem is described, therefore the the headline "The solution" is wrong before these lines.

2022-01-04 14:54 UTC, froschdesign commented on docs/book/v4/cookbook/provide-a-request-id.md
> +The answer is deceptively simple: you can provide a [delegator factory](https://docs.mezzio.dev/mezzio/v3/features/container/delegator-factories/) for decorator on the service that converts the Swool
Maybe it is _simple_ for you but it does not mean that it applies to others as well. So do not use "simple" or "easy" in the documentation.

2022-01-04 15:14 UTC, weierophinney commented on docs/book/v4/cookbook/provide-a-request-id.md
> +This poses a problem: normally you will use middleware to propagate changes to the request.
Updated.

2022-01-04 15:14 UTC, weierophinney commented on docs/book/v4/cookbook/provide-a-request-id.md
> +The answer is deceptively simple: you can provide a [delegator factory](https://docs.mezzio.dev/mezzio/v3/features/container/delegator-factories/) for decorator on the service that converts the Swool
Updated.

2022-01-07 17:49 UTC, merged