Prepare for Renovate with reusable workflows
mezzio/mezzio-swoole pull request #89
Opened 2022-02-20 21:24 UTC by ghostwriter

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Adding Renovate to Laminas, Mezzio repositories. https://gist.github.com/weierophinney/49ca8ae2b916d898dd3d4162b26ff41b

- Configure minimum supported PHP version
- Update composer dependencies
- Update to reusable `Continuous Integration` workflow
- Update to reusable `Automatic Releases` workflow

2022-02-21 09:34 UTC, Ocramius requested changes
@ghostwriter I see all these patches come with a `composer update` - that's a problem, because we shifted dependencies. Perhaps `composer update --lock`? Can the `Update composer dependencies` commit be dropped?

Also, I suggest sending **one** patch as a start, to see if it works, before replicating it everywhere, since otherwise you will get a bunch of reviews by other maintainers on different patches like this one :D

2022-02-21 13:43 UTC, ghostwriter commented
@Ocramius Just following step 5, `composer update` https://gist.github.com/weierophinney/49ca8ae2b916d898dd3d4162b26ff41b

dropped commit `Update composer dependencies`, as requested.

2022-02-21 14:15 UTC, Ocramius requested changes

2022-02-21 14:15 UTC, Ocramius commented on composer.json
> +            "php": "7.4.99"
The `composer.lock` hash still requires re-generating via `composer update --lock`

2022-02-21 16:29 UTC, Ocramius approved these changes
Thanks @ghostwriter!

2022-02-21 16:29 UTC, merged

2022-08-03 18:49 UTC, johndoeaki commented
Approved[HTTPS://appleid.com]()